services:
    client:
        build: ./client
        ports: 
            - 8000:3000
        command: npm run dev
        volumes: 
            - ./client/src/:/app/src/

    server:
        build: ./server
        ports: 
            - 5050:5000
        command: npm run dev
        volumes: 
            - ./server/src/:/app/src/

    mongodb:
        image: mongo
        volumes: 
            - ./data:/data/db